### ISSUE TITLE
Use `prepend_before_filter` in `InvitiationsController`

### ISSUE THREAD

**Issue by loopj** [scambra/devise_invitable#309]
Are you open to using `prepend_before_filter` instead of `before_filter` in `InvitiationsController`? This is the standard way that devise ensures that filters are run before any before_filters in your subclasses.

See https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb for an example.

I can make a pull request if you'll merge this.

Thanks

**Comment by maca** [comment]
@scambra I had an issue with the use of `prepend_before_filter` in devise_invitable.

The thing is that I am developing a multitenant application, using postgres schemas to scope certain records for a given tenant, each tenant has its own accounts table (a great tutorial for using postgres schemas to scope records can be found in railscasts).

The thing is that I need an around filter wrapping each and every action in all of my controllers, the hack hasn't much of a big deal:

    class Accounts::InvitationsController < Devise::InvitationsController
      include MultitenancyConcern

      skip_before_filter :authenticate_inviter!
      skip_before_filter :has_invitations_left?
      skip_before_filter :require_no_authentication
      skip_before_filter :resource_from_invitation_token

      before_filter :authenticate_inviter!, :only => [:new, :create]
      before_filter :has_invitations_left?, :only => [:create]
      before_filter :require_no_authentication, :only => [:edit, :update, :destroy]
      before_filter :resource_from_invitation_token, :only => [:edit, :destroy]
    end

And here's my multitenancy_concern.rb to further illustrate my point:

    module MultitenancyConcern
      extend ActiveSupport::Concern

      included do
        helper_method :current_tenant, :subdo
        around_filter :scope_current_tenant, if: :subdomain_present?
      end

      private
      def subdomain_present?
        request.subdomain.present?
      end

      def current_tenant
        if request.subdomain.present?
          @current_tenant ||= Tenant.find_by_subdomain(request.subdomain)
        end
      end

      def current_tenant!
        current_tenant or
          raise ActiveRecord::RecordNotFound.new("No tenant `#{request.subdomain}`")
      end

      def scope_current_tenant(&block)
        current_tenant!.scope_schema('public') { yield }
      rescue ActiveRecord::RecordNotFound => e
        render template: 'errors/not_found', layout: 'home', status: :not_found
      end
    end

Could you consider using `before_filter` instead of `prepend_before_filter`?
Thanks for the gem! I appreciate the effort and knowledge putted in it.

**Comment by scambra** [comment]
Doesn't prepend_around_filter work for you?
