### ISSUE TITLE
mysterious generate_token method

### ISSUE THREAD

**Issue by jjb** [scambra/devise_invitable#443]
`generate_token` is invoked here: https://github.com/scambra/devise_invitable/blob/master/lib/devise_invitable/model.rb#L291

However I can't find any definition of such a method in the devise_invitable, devise, or rails codebases.

I also searched for various things to see if it's generated at runtime and didn't find anything.

I also poked around in Pry and it seems to be undefined.

```
app(dev)> cd User
app(dev)> show-method generate_token
Error: Couldn't locate a definition for generate_token!
app(dev)> show-method invitation_token

From: /Users/john/medstro/devise_invitable/lib/devise_invitable/model.rb @ line 290:
Owner: Devise::Models::Invitable::ClassMethods
Visibility: public
Number of lines: 3

def invitation_token
  generate_token(:invitation_token)
end
app(dev)> generate_token(:invitation_token)
NoMethodError: undefined method `generate_token' for User(no database connection):Class
from /Users/john/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activerecord-4.0.3/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
```

**Comment by hsson** [comment]
I'm using devise_invitable 1.1.8 and here the generate_token method is called but an exception is raised since it can't be found anywhere. This totally breaks the gem and I can't invite any user. I'm running Devise 3.5.10 which is as high as I can go considering other dependencies. Can I upgrade devise_invitable or should I downgrade it? Any recommendations?

**Comment by scambra** [comment]
You should upgrade devise_invitable to latest
