### ISSUE TITLE
Devise Parameter Sanitizer not working?

### ISSUE THREAD

**Issue by volkanunsal** [scambra/devise_invitable#518]
I have not been able to get the `devise_parameter_sanitizer` to work in my `invitations_controller.rb`. Here is what I am seeing in the console. Can anyone shed some light on this?

(Note that this happens in the `create` action.)

```bash

[1] pry(#<Users::InvitationsController>)> devise_parameter_sanitizer
  => #<Devise::ParameterSanitizer:0x007fdbb1bba0a0
   @blocks={},
   @params=
    {"invite"=>{"name"=>"Volkan", "email"=>"me@example.com"},
     "controller"=>"users/invitations",
     "action"=>"create"},
   @permitted={:invite=>[:email, :name]},
  [2] pry(#<Users::InvitationsController>)> devise_parameter_sanitizer.sanitize(:invite)
  => {}
```

**Comment by ejaypcanaria** [comment]
I just encounter this issue. I'm using a link to invite user so I had to provide param hash instead of the form provided in the generated view.

`devise_parameter_sanitizer.sanitize(:invite)` will fetch the `resource_name` (which is the invitable model - usually User model) in the params not the `:invite` symbol.

To fix the issue, you need to wrap the parameter in the resource name like this assuming your model is user:

`params = { user: {"name" => "John", "email" => "john@example.com"} }`

Hope this helps.
