### ISSUE TITLE
Unpermitted parameter for nested attributes

### ISSUE THREAD

**Issue by jarkelen** [scambra/devise_invitable#561]
In my app an `user` has_many `teamroles` by a has_many :through relationship.
When I create a user, the parameters look like this:

````
Processing by InvitationsController#create as HTML
  Parameters: {"user"=>{"name"=>"Test", "email"=>"test@test.nl", "teamrole_ids"=>["1", "2"]}, "commit"=>"Save"}
Unpermitted parameter: teamrole_ids
````

This results in a `unpermitted parameter` error, despite this in the `ApplicationController`:

    devise_parameter_sanitizer.for(:invite) << :teamrole_ids

How should I make `teamrole_ids` permitted?

**Comment by scambra** [comment]
Is that line in a before_filter? are you sure that before_filter is run for create invitation action?

**Comment by jarkelen** [comment]
Yes, that is in a method `configure_permitted_parameters` and called with:

`before_filter :configure_permitted_parameters, if: :devise_controller?`

**Comment by scambra** [comment]
It's unrelated to devise_invitable, more a strong parameters or rails4 question. Here it's as it works:

The permitted scalar types are String, Symbol, NilClass, Numeric, TrueClass, FalseClass, Date, Time, DateTime, StringIO, IO, ActionDispatch::Http::UploadedFile and Rack::Test::UploadedFile.

To declare that the value in params must be an array of permitted scalar values map the key to an empty array:
params.require(:question).permit(:question_details, :question_content, :user_id, :accepted_answer_id, :province_id, :city, :category_ids => [])

So you could try adding a hash instead of symbol:
devise_parameter_sanitizer.for(:invite) << {:teamrole_ids => []}

I haven't tested, but I think it should work

**Comment by jarkelen** [comment]
Unfortunately, still the same 'unpermitted parameter` error. But if it's unrelated to devise_invitable, let's close this issue and I look further to solve this. Thanks for your help!

**Comment by scambra** [comment]
try asking devise, devise invitable uses devise_parameter_sanitizer, which comes from devise, maybe they know better how to do that

Also you can try using block:
devise_parameter_sanitizer.for(:invite) { |u| u.permit(*resource_class.invite_key_fields, :teamrole_ids => []) }
