### ISSUE TITLE
invitation emails are not being send using sendgrid

### ISSUE THREAD

**Issue by asnad** [scambra/devise_invitable#570]
I am using sendgrid to send emails my all other emails (except devise) are being send on production but all the devise emails including confirmation and invitation emails are not being send here is my production.rb
config.action_mailer.raise_delivery_errors = false
  config.action_mailer.default_url_options = { :host => 'startmarket.herokuapp.com' }
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    address: 'smtp.sendgrid.net',
    port: 587,
    domain: 'heroku.com',
    authentication: "plain",
    enable_starttls_auto: true,
    user_name: ENV["SENDGRID_USERNAME"],
    password: ENV["SENDGRID_PASSWORD"]
  }

**Comment by scambra** [comment]
If confirmation emails are not working, then it's a devise issue, not devise_invitable, because devise_invitable uses devise mailer to send its email. You should open issue on plataformatec/devise

**Comment by HatStephens** [comment]
@asnad - had the same problem. found a SO with solution:
Try adding the following to your production.rb file:
  config.action_mailer.perform_deliveries = true

I also set the following to true because that's what it said, but maybe you don't need to?
  config.action_mailer.raise_delivery_errors = true
