### ISSUE TITLE
Token Missing

### ISSUE THREAD

**Issue by andricicezar** [scambra/devise_invitable#627]
[I tried this tutorial](https://github.com/scambra/devise_invitable/wiki/Customizing-for-different-Invite-use-cases-(emails-etc.)), but when I am sending an invite, the link generated doesn't contain the token.

Can you help me?

Demo: https://github.com/andricicezar/devise_invitable_test

In console:
```
rails c
irb(main):001:0> User.invite_student!(:email => "example@com.com")
  User Load (0.9ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["email", "example@com.com"]]
  User Load (1.2ms)  SELECT  "users".* FROM "users" WHERE "users"."invitation_token" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["invitation_token", "cd779742b8ba370fad25fec03d4d71677e1e259b0f56ed805c0680c507f680cd"]]
   (0.1ms)  begin transaction
  SQL (2.4ms)  INSERT INTO "users" ("email", "encrypted_password", "invitation_token", "invitation_created_at", "invitation_sent_at", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?)  [["email", "example@com.com"], ["encrypted_password", "$2a$10$5P7LYywJ/szl1oDjPoInJ.DvM1EdXSPKnNIZtIhlHGMvjL6Gpr4K."], ["invitation_token", "cd779742b8ba370fad25fec03d4d71677e1e259b0f56ed805c0680c507f680cd"], ["invitation_created_at", "2016-02-05 16:40:57.139264"], ["invitation_sent_at", "2016-02-05 16:40:57.139264"], ["created_at", "2016-02-05 16:40:57.141055"], ["updated_at", "2016-02-05 16:40:57.141055"]]
   (1.3ms)  commit transaction
DEPRECATION WARNING: `#deliver` is deprecated and will be removed in Rails 5. Use `#deliver_now` to deliver immediately or `#deliver_later` to deliver through Active Job. (called from deliver_invitation at /vagrant/testinvitable/app/models/concerns/invitable.rb:9)
  Rendered invite_mailer/student_invitation_instructions.html.erb (8.9ms)

InviteMailer#student_invitation_instructions: processed outbound mail in 276.8ms
RuntimeError: --- !ruby/object:Mail::Body
boundary: 
preamble: 
epilogue: 
charset: US-ASCII
part_sort_order:
- text/plain
- text/enriched
- text/html
parts: !ruby/array:Mail::PartsList []
raw_source: |
  <p>Student:: Hello example@com.com</p>

  <p><a href="http://localhost:3000/users/invitation/accept">Accept invitation</a></p>

    <p>This invitation will be due in February 05, 2016 04:40 PM.</p>

  <p>If you don't want to accept the invitation, please ignore this email.<br />Your account won't be created until you access the link above and set your password.</p>
encoding: 7bit
```

The file:
```
module Invitable
  extend ActiveSupport::Concern

  included do
    attr_writer :invitation_instructions

    def deliver_invitation(options = {})
      if @invitation_instructions.present?
        ::Devise.mailer.send(@invitation_instructions, self).deliver
      else
        super
      end
    end
  end

  module ClassMethods
    def invite_student!(attributes={}, invited_by=nil)
      self.invite!(attributes, invited_by) do |invitable|
        invitable.invitation_instructions = :student_invitation_instructions
      end
    end
  end
end
```

**Comment by scambra** [comment]
I guess you are not using @token in student_invitation_instructions view.

Here is how default invitation_instructions view does:
accept_invitation_url(@resource, :invitation_token => @token)

**Comment by andricicezar** [comment]
I use that. Check here: https://github.com/andricicezar/devise_invitable_test/blob/master/app/views/invite_mailer/student_invitation_instructions.html.erb

**Comment by scambra** [comment]
Probably tutorial is outdated. Here is current deliver_invitation method:

```ruby
  def deliver_invitation(options = {})
      generate_invitation_token! unless @raw_invitation_token
      self.update_attribute :invitation_sent_at, Time.now.utc unless self.invitation_sent_at
      send_devise_notification(:invitation_instructions, @raw_invitation_token, options)
  end
```

If you change deliver_invitation you should do same as deliver_invitation, use generate_invitation_token if not generated, and use send_devise_notification, including the raw token.

Also, student_invitation_instructions in mailer should accept token in parameter and set @token

```ruby
class InviteMailer < Devise::Mailer
  def student_invitation_instructions(record, token, opts={})
    @token = token
    devise_mail(record, :student_invitation_instructions, opts)
  end
end
```

Probably, it would be better not to define deliver_invitation, and change invitation_instructions in your mailer (in this case you need to use attr_accessor instead of attr_writer):

```ruby
class InviteMailer < Devise::Mailer
  def invitation_instructions(record, token, opts={})
    @token = token
    devise_mail(record, record.invitation_instructions || :invitation_instructions, opts)
  end
end
```

**Comment by andricicezar** [comment]
Ok, how should look like `invite_student!`? I can't figure it out.

**Comment by scambra** [comment]
I don't think invite_student! needs changes. Still not working?

**Comment by andricicezar** [comment]
Yes. It is working! Thanks!

**Comment by andricicezar** [comment]
I updated the [wiki](https://github.com/scambra/devise_invitable/wiki/Customizing-for-different-Invite-use-cases-(emails-etc.)) too. Check if is ok.

**Comment by scambra** [comment]
Thanks a lot for updating wiki

**Comment by artem-galas** [comment]
Hi!

I have a question: I use [devise_asyn](https://github.com/mhfs/devise-async)c that uses DeleayJob, and when I send am email via a custom method, I get nil instead of the parameter I wrote. Can you give me a piece of advice, what could cause it?

**Comment by scambra** [comment]
DeviseInvitable calls send_devise_notification(:invitation_instructions, @raw_invitation_token, options), just like devise does for recoverable, send_devise_notification(:reset_password_instructions, token, {}).

DeviseAsync overrides send_devise_notification and save mailer and arguments to send mail later, with same arguments. Token is a parameter in invitation_instructions, and it sets @token, ensure your view is using @token, as DeviseInvitable mailer views do, instead of @resource.raw_invitation_token which will be nil when using DeviseAsync.

**Comment by artem-galas** [comment]
@scambra 

Thanks for clarification. But the problem is not with the token itself, but in the transition of `record.invitation_instructions` - when I am doing it, I get nil instead of the delivered parameter.

I'm trying to do the same in the tutorial

Or I maybe I can just not use devise_async ?

**Comment by scambra** [comment]
Have you tried to use devise async without changing anything in devisemailer or devise model?

**Comment by artem-galas** [comment]
Yes, I have. Everything woks great. But if I made these changes i always get invitation_instructions instead `student_invitation_instructions` (for eq)

**Comment by scambra** [comment]
attr_accessor  will be lost with DeviseAsync, because deliver_later will load resource from DB, and attr_accessors are not saved into DB.

You could override deliver_invitation, to call send_devise_invitation with :student_invitation_instructions when needed:
https://github.com/scambra/devise_invitable/blob/master/lib/devise_invitable/models.rb#L198

Or, you could override devise_mail_later, although you must be careful in order not to break devise mails:
https://github.com/mhfs/devise-async/blob/master/lib/devise/async/model.rb#L52
