### ISSUE TITLE
README section on testing seems to indicate wrong Ruby version

### ISSUE THREAD

**Issue by rally25rs** [scambra/devise_invitable#688]
According to the README section on running the tests:

> To test DeviseInvitable for the ActiveRecord ORM with RVM, Ruby 2.0.0:
>
>   rvm use 2.0.0
>   ...
>   rake test DEVISE_ORM=active_record

However, "activesupport requires Ruby version >= 2.2.2":

```
~/Projects/devise_invitable (master) : bundle install
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 11.3.0
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.1
Using thread_safe 0.3.5
Using tzinfo 1.2.2

Gem::InstallError: activesupport requires Ruby version >= 2.2.2.
An error occurred while installing activesupport (5.0.0.1), and Bundler cannot continue.
Make sure that `gem install activesupport -v '5.0.0.1'` succeeds before bundling.
```

-----

Also, I think the last command is missing `bundle exec` and should be:

> bundle exec rake test DEVISE_ORM=active_record

**Comment by scambra** [comment]
devise invitable works with ruby >= 2.0 and devise >= 4.0, however devise requires ruby >= 2.1
Devise supports rails 4.1, 4.2 and 5.0. If you use rails 4.x you can use ruby 2.1, but if you use 5.0 you must use >= 2.2.2

I'm chaning README for ruby 2.2.2 because it's not possible to test with 2.0 (devise needs 2.1) and lastest rails may be installed, which requires 2.2.2
