### ISSUE TITLE
Disallow invitations with existing email 

### ISSUE THREAD

**Issue by teosz** [scambra/devise_invitable#692]
Hello,
Is there a way to don't let invites for existing user happen?

**Comment by scambra** [comment]
Can you explain more? Are you getting invitations for registered users or users who already accepted invitation? Or are you talking about disable resending invitations?

**Comment by teosz** [comment]
I'm getting for invitations for users who already accepted the invitation.
I'm not talking about resending invitations.

**Comment by scambra** [comment]
It shouldn't happen, deviseinvitable looks for existing user with email and check if it has a pending invitation:

```ruby
          elsif !invitable.invited_to_sign_up? || !self.resend_invitation
            invite_key_array.each do |key|
              invitable.errors.add(key, :taken)
            end
          end
```

Are you using some custom code?

If you look for user with that email, what invited_to_sign_up? returns?

**Comment by teosz** [comment]
The user manually created by seed. `invitable.invited_to_sign_up?` returns true.

**Comment by scambra** [comment]
You must be creating user with invitation_token present, so invited_to_sign_up? is true, in that case is ok to allow sending invitation because user didn't accept invitation, and resend_invitations is enabled.

You didn't post whole seed for user, so just guessing

**Comment by codeinaire** [comment]
I'm getting this issue as well using `~> 1.7`

**Expected**
I create a new user, invite the new user, and the new user accepts the invitation. When I run `.invite!` again the invitation process isn't run and it returns false.

**Actual**
I create a new user, invite the new user, and the new user accepts the invitation. However, when I invite the user again the invitation process is run and returns `#<Delayed::Backend::ActiveRecord::Job:0x00007fbf87ddf678 ...>` object.

The steps involved to replicate:

```
new_user = User.new({account: account, subdomain: 'testdomain', email: 'test@user.com'})
new_user.invite!
=> true
new_user.invited_to_sign_up?
=> true
new_user.accept_invitation!
=> #<Delayed::Backend::ActiveRecord::Job:0x00007fbf87ddf678 ... >
new_user.invited_to_sign_up?
=> false
new_user.invite!
=> true
```

The one time I've gotten it to fail is when I run the `User.new...` step with the same details as another user and run the`.invite!` method. It fails because a user already exists.

**Comment by scambra** [comment]
accept_invitation! should return true or false. Have you changed any method in your model?

Your test is not valid, you should use User.invite! instead of User.new and user.invite!, check to avoid inviting existing user is in User.invite!, if you call instance method instead of class method, you are skipping DeviseInvitable checks, and you must do whatever checks you want.
