### ISSUE TITLE
deliver_invitation sends email (possible wiki just needs update)

### ISSUE THREAD

**Issue by d-a-v-e** [scambra/devise_invitable#699]
The wiki explains how to generate a user with an invitation_token

```
user = User.invite!(:email => "new_user@example.com", :name => "John Doe") do |u|
  u.skip_invitation = true
end
```

It then goes on to explain that `invitation_sent_at` must be set using `user.deliver_invitation` but this seems to trigger the email. 

possibly a separate bug, but I skipped this step (to see if it was triggering the email) and was still able to accept the invite and create an account.

**Comment by scambra** [comment]
invite! with skip_invitation skips setting invitation_sent and sending email. Depending in your needs, if you deliver invitation using different system than email, you will have to set invitation_sent_at (if you want to track timestamp when invitation is sent), or use deliver_invitation to send email (if you want to do later).

I don't see what wiki page explains to call deliver_invitation

**Comment by krue-doug** [comment]
@scambra 

https://github.com/scambra/devise_invitable/blob/e93ced514048db46d8f15de82bb3e4a717354b3d/README.rdoc

> 
> When skip_invitation is used, you must also then set the invitation_sent_at field when the user is sent their token. Failure to do so will yield Invalid invitation token error when the user attempts to accept the invite. You can set it like so:
> 
> user.deliver_invitation

I thought exactly the same thing  as @d-a-v-e. That paragraph tells me if I use `skip_invitation` then I can make sure to set the sent_at with this method. I would also assume that the invitation is not sent because I had `skip_invitation` set.

In this example (https://github.com/scambra/devise_invitable/wiki/Customizing-for-different-Invite-use-cases-(emails-etc.)), you have this:

```
    class InvitationsController < Devise::InvitationsController
      def create
        @from    = params[:from]
        @subject = params[:invite_subject]
        @content = params[:invite_content]
        
        @user = User.invite!(params[:user], current_user) do |u|
          u.skip_invitation = true
        end

        NotificationMailer.invite_message(@user, @from, @subject, @content).deliver if @user.errors.empty?
        @user.invitation_sent_at = Time.now.utc # mark invitation as delivered

        if @user.errors.empty?
          flash[:notice] = "successfully sent invite to #{@user.email}"
          respond_with @user, :location => root_path
        else
          render :new
        end
      end
    end
```

I noticed `@user` is never saved after sitting the invitation_sent_at, how does devise_invitable save it?

**Comment by scambra** [comment]
I fixed explanation in README. About wiki, I don't think it's saving column so I have changed it, but wiki is contributed by users and I don't supervise it.
