### ISSUE TITLE
does not invoke after_confirmation callback

### ISSUE THREAD

**Issue by ninjarails** [scambra/devise_invitable#711]
i found that this module does not invoke after_confirmation when user accept invitation. This is related to this code part.
https://github.com/scambra/devise_invitable/blob/master/lib/devise_invitable/model.rb#L97

i think it makes more sense to call `self.confirm` instead of `self.confirmed_at = self.invitation_accepted_at if self.respond_to?(:confirmed_at)` when devise confirmable module is enabled.

**Comment by ninjarails** [comment]
@scambra I can make a PR if you like.

**Comment by scambra** [comment]
Not sure if good idea, confirm may fail if confirmation is expired or record is already confirmed.

It probably never happens, because devise invitable skips setting confirmation_sent_at and record shouldn't be confirmed when accepting invtation. But if someone change how it works it could make accepting invitation fail, maybe calling after_confirmation in accept_invitation! would be better.
