### ISSUE TITLE
Invitation Token is invalid—Safari only

### ISSUE THREAD

**Issue by micahredding** [scambra/devise_invitable#720]
When clicking on an invitation link, my setup asks you to select a password. In Chrome and other browsers, this works, but in Safari, it generates an error "invitation token is invalid".

**Comment by nikhilthombare** [comment]
Same issue facing to me when use devise gem - http://localhost:3000/invitation/accept?invitation_token=8pS7Qkf5Az63Tx4yZT1 Its show be "invitation token is invalid" on safari but other browser is working fine. 

I observe logs then find 

Fail case:
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"+SYYohmuZIM4RHgMyUupopWfc=", "user"=>{"invitation_token"=>"**xyz@gmail.com**", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Set my password"}

Pass case: 
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"gVpsCr3bfAc9DR52JDBbcVj2QveUoeP+GoOdSI3KCoc=", "user"=>{"invitation_token"=>"**iF5AffyFsbe4jfn3zRVx**", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Set my password"}

**Comment by scambra** [comment]
Can you check form with web inspector? it should have an input hidden with invitation token, not email.

**Comment by nikhilthombare** [comment]
I already check same request parameter with safari and chrome browser. its invitation_token hidden field issue with different params one is email and other is token. 

<img width="1173" alt="screen shot 2018-01-25 at 6 08 05 pm" src="https://user-images.githubusercontent.com/6488354/35388679-c033ab16-01fa-11e8-80b4-877173c2f385.png">
<img width="1181" alt="screen shot 2018-01-25 at 6 07 48 pm" src="https://user-images.githubusercontent.com/6488354/35388680-c059e042-01fa-11e8-94b1-3b519d13610c.png">

**Comment by scambra** [comment]
Edit action loads invitable resource with token here:
https://github.com/scambra/devise_invitable/blob/master/app/controllers/devise/invitations_controller.rb#L100

token must be right because you would be redirected in other case.

Then invitation token from param is written to resource, because token from database is a hash:
https://github.com/scambra/devise_invitable/blob/master/app/controllers/devise/invitations_controller.rb#L42

And edit view is rendered, which outputs hidden_field for invitation token:
https://github.com/scambra/devise_invitable/blob/master/app/views/devise/invitations/edit.html.erb#L5

I don't see how it may work different in any browser.

**Comment by nikhilthombare** [comment]
Here I fixed this issue. Issue is related to autofilled value with email for reset_password_token and invitation_token. you need to generate view and add read only for avoid autofill. 

I added and fixed for me 
    <%= f.hidden_field :invitation_token, **readonly: true** %>
    
     <%= f.hidden_field :reset_password_token, **readonly: true** %>

**Comment by scambra** [comment]
I added readonly to invitation token, it looks kind of hack, it doesn't make sense browser autofills an input hidden, probably safari bug, but I don't think there is another way to fix in safari

**Comment by brodyhoskins** [comment]
I'm running into this issue in Safari 15 even with `readonly: true`. It's still sending the email address as the `invitation_token`.
