### ISSUE TITLE
Any way to control the layout?

### ISSUE THREAD

**Issue by christopherstyles** [scambra/devise_invitable#729]
I’ve tried all the methods outlined here: https://github.com/plataformatec/devise/wiki/How-To:-Create-custom-layouts  …but still no luck. Any ideas?

**Comment by christopherstyles** [comment]
I managed to get this working by overriding the `devise_mailer` method in my model:

```ruby
# app/models/example.rb
class Example < ActiveRecord::Base
  def devise_mailer
    DeviseExampleMailer
  end
end
```

```ruby
# app/mailers/devise_example_mailer.rb
class DeviseExampleMailer < Devise::Mailer
  layout 'example_mailer'
end
```

**Comment by wdiechmann** [comment]
and this is still true :)

**Comment by scambra** [comment]
It isn't related to devise invitable, and also it's linking a wiki about layout in controllers when he wants to change layout for mailer

**Comment by wdiechmann** [comment]
well - ( I'm trying to use custom mailer layouts per 'user' ) - and I'm inclined to agree with you @scambra :)

adding `config.mailer=CustomDeviseMailer` to my `config/initializers/devise.rb` did the trick for me with Rails 5.2 / Ruby 2.5.1 - and Devise 4.5.0 and Devise Invitable 1.7.5 -

I can use `app/views/users/mailer/invitation_instructions.html.haml` but once I start to customize my `CustomDeviseMailer` (overriding two methods in order to render special layouts) - things go south (like she starts using the original template like: 

```
Rendering /Users/walther/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise_invitable-1.7.5/app/views/devise/mailer/invitation_instructions.html.erb within layouts/alco_mailer
Rendered /Users/walther/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise_invitable-1.7.5/app/views/devise/mailer/invitation_instructions.html.erb within layouts/alco_mailer (8.3ms)
CustomDeviseMailer#invitation_instructions: processed outbound mail in 56.5ms
Completed 500 Internal Server Error in 268ms (ActiveRecord: 12.9ms)
```

My custom mailer looks like:

```
class CustomDeviseMailer < Devise::Mailer
  layout "alco_mailer"

  def invitation_instructions(record, token, opts={})
    @layout = record.account.invitation_template
    super
  end

  # Override to include custom layouts
  def devise_mail(record, action, opts={})
    initialize_from_record(record)
    mail(headers_for(action, opts)) do |format|
      format.html { render layout: @layout }
    end
  end

end
```

I probably should be "barking up the Devise tree" - would you by any chance what I leave out with this 'specialization', I mean; I've been trawling through the DeviseInvitable and Devise gems, and I somehow suspect the headers_for() setting template_path - but I cannot 'get to it' - any idea?

**Comment by wdiechmann** [comment]
okay - I'll leave this as is - but if you're interested in knowing the answer, I've added [a wiki-page to Devise](https://github.com/plataformatec/devise/wiki/How-To:-use-special-layouts-for-DeviseMailer---per-user)
