### ISSUE TITLE
@resource is nil:NilClass in mail template using User.invite!

### ISSUE THREAD

**Issue by Emilie-thp** [scambra/devise_invitable#839]
Hello, 

I try to use the `User.invite!` method somewhere in my rails app and I have a problem with the invitation_instruction email sending... 
Everything is going well (my user is created in db, with its token, no problem) until the email sending !
When the email is built to be sent, the **`@resource` variable is nil** , so I receive this error right after the outbound email processing...
```
undefined method `firstname' for nil:NilClass excluded from capture: No host specified, no public_key specified, no project_id specified
```
If I remove all the parts using `@resource` attributes within the email view, the email is sent without any problem !
Do you know what could cause this problem ? 

I tried to override the devise mailer with a custom one to use `binding.pry` inside and I can see that @resource is well defined in this method, but right after it raises an exception (cf.screen below)
```
    22: def initialize_from_record(record)
    23:   @scope_name = Devise::Mapping.find_scope!(record)
    24:   @resource   = instance_variable_set("@#{devise_mapping.name}", record)
    25: end
````

![Capture d’écran 2020-11-16 à 13 03 23](https://user-images.githubusercontent.com/55739570/99265710-449bea80-2822-11eb-8458-b5bbd3960cc7.png)

Your help would be much appreciated, thank you in advance !

**Comment by scambra** [comment]
I don't know, I don't see why @resource is set in that mailer method, but it's nil in view. Neither devise nor devise invitable set @resource in other place than initialize_from_record, that's a devise method, and deviseinvitable only adds invitation_instructions method to mailer, which calls devise_mail method.

If your custom mailer is getting right user record in invitation_instructions method, then this issue is not devise invitable related. It would be a devise issue, or some error in your custom code.
