### ISSUE TITLE
Has validate_on_invite become useless? 

### ISSUE THREAD

**Issue by dkolistratova** [scambra/devise_invitable#881]
Looks like this line https://github.com/scambra/devise_invitable/commit/986f49b1625592c4622a99b6cfb6073b1a234b7c#diff-37b9a03c69160b66e982336a7f6ebc74d9df4c2835c44810c0d5c978bef2c22cL327 makes "validate=false" always, not giving any choice. How to enable that if I need?

**Comment by scambra** [comment]
No, the change only makes invite instance method to respect validate_on_invite when is called by custom code, without calling class method. When calling class method, instance method doesn't need to run validations, as they are run by class method if the setting is enabled.

valid? will be called on line 318, in the class method, if validate on invite is enabled, as before.

Before the change, line 161 was calling save skipping validation `save(validate: false)`, and this change uses value from validate_on_invite, so line 328 is passing validate: false to skip validation on line 161 instead of following validate_on_invite, as validation would have run on line 318.
